import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useTenant } from "@/hooks/useTenant";
import { useBusinessConfig } from "@/hooks/useBusinessConfig";
import { Loader2, FileText, Receipt, CheckCircle } from "lucide-react";
import { format } from "date-fns";

interface CustomOrder {
  id: string;
  order_number: string;
  customer_id: string | null;
  design_type: string | null;
  fabric: string | null;
  quoted_price: number | null;
  deposit_paid: number | null;
  collection_date: string | null;
  due_date: string | null;
  invoice_id: string | null;
  customers?: { name: string; email: string | null; phone: string | null } | null;
}

interface OrderToInvoiceModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  order: CustomOrder | null;
  onSuccess: () => void;
}

export function OrderToInvoiceModal({ open, onOpenChange, order, onSuccess }: OrderToInvoiceModalProps) {
  const { toast } = useToast();
  const { tenantId } = useTenant();
  const { currencySymbol } = useBusinessConfig();
  const [loading, setLoading] = useState(false);
  const [notes, setNotes] = useState("");
  const [dueDate, setDueDate] = useState("");

  useEffect(() => {
    if (order && open) {
      setNotes(`Custom Order: ${order.order_number} - ${order.design_type || "Custom Design"}${order.fabric ? ` (${order.fabric})` : ""}`);
      setDueDate(order.collection_date || order.due_date || "");
    }
  }, [order, open]);

  if (!order) return null;

  const quotedPrice = order.quoted_price || 0;
  const depositPaid = order.deposit_paid || 0;
  const balanceDue = quotedPrice - depositPaid;

  const handleGenerateInvoice = async () => {
    if (!tenantId || !order) return;

    setLoading(true);
    try {
      const { data: userData } = await supabase.auth.getUser();

      // 1. Create the invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from("invoices")
        .insert({
          tenant_id: tenantId,
          invoice_number: "", // Auto-generated by DB trigger
          client_name: order.customers?.name || "Walk-in Customer",
          client_email: order.customers?.email || null,
          client_phone: order.customers?.phone || null,
          invoice_date: new Date().toISOString().split("T")[0],
          due_date: dueDate || null,
          status: depositPaid > 0 ? "partial" : "unpaid",
          subtotal: quotedPrice,
          tax_rate: 0,
          tax_amount: 0,
          total_amount: quotedPrice,
          paid_amount: depositPaid,
          notes: notes || null,
          created_by: userData.user?.id || null,
        })
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // 2. Create invoice line item
      const { error: itemError } = await supabase
        .from("invoice_items")
        .insert({
          invoice_id: invoice.id,
          tenant_id: tenantId,
          description: `${order.design_type || "Custom Design"} - ${order.order_number}${order.fabric ? ` (${order.fabric})` : ""}`,
          quantity: 1,
          unit_price: quotedPrice,
          amount: quotedPrice,
          item_type: "service",
        });

      if (itemError) throw itemError;

      // 3. If deposit was paid, create a payment receipt for it
      if (depositPaid > 0) {
        const { error: receiptError } = await supabase
          .from("payment_receipts")
          .insert({
            tenant_id: tenantId,
            receipt_number: "", // Auto-generated
            invoice_id: invoice.id,
            client_name: order.customers?.name || "Walk-in Customer",
            client_email: order.customers?.email || null,
            amount_paid: depositPaid,
            payment_method: "cash",
            payment_date: order.collection_date || new Date().toISOString().split("T")[0],
            notes: "Initial deposit for custom order",
            created_by: userData.user?.id || null,
          });

        if (receiptError) {
          console.warn("Failed to create deposit receipt:", receiptError);
        }
      }

      // 4. Link invoice to custom order
      const { error: updateError } = await (supabase
        .from("custom_orders") as any)
        .update({ invoice_id: invoice.id })
        .eq("id", order.id);

      if (updateError) throw updateError;

      toast({
        title: "Invoice Generated",
        description: `Invoice ${invoice.invoice_number} created successfully${depositPaid > 0 ? " with deposit recorded" : ""}`,
      });

      onSuccess();
      onOpenChange(false);
    } catch (error: any) {
      console.error("Error generating invoice:", error);
      toast({ title: "Error", description: error.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            Generate Invoice
          </DialogTitle>
          <DialogDescription>
            Create an invoice from this custom order for payment tracking
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Order Summary */}
          <div className="bg-muted/50 p-4 rounded-lg space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Order:</span>
              <span className="font-medium">{order.order_number}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Customer:</span>
              <span className="font-medium">{order.customers?.name || "Walk-in"}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Design:</span>
              <span className="font-medium capitalize">{order.design_type || "Custom"}</span>
            </div>
          </div>

          {/* Financial Summary */}
          <div className="border rounded-lg p-4 space-y-2">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Quoted Price:</span>
              <span className="font-medium">{currencySymbol}{quotedPrice.toLocaleString()}</span>
            </div>
            {depositPaid > 0 && (
              <div className="flex justify-between text-green-600">
                <span className="flex items-center gap-1">
                  <CheckCircle className="h-3 w-3" />
                  Deposit Paid:
                </span>
                <span className="font-medium">-{currencySymbol}{depositPaid.toLocaleString()}</span>
              </div>
            )}
            <div className="flex justify-between pt-2 border-t font-bold">
              <span>Balance Due:</span>
              <span className="text-primary">{currencySymbol}{balanceDue.toLocaleString()}</span>
            </div>
          </div>

          {/* Due Date */}
          <div className="space-y-2">
            <Label htmlFor="dueDate">Invoice Due Date</Label>
            <Input
              id="dueDate"
              type="date"
              value={dueDate}
              onChange={(e) => setDueDate(e.target.value)}
            />
          </div>

          {/* Notes */}
          <div className="space-y-2">
            <Label htmlFor="invoiceNotes">Invoice Notes</Label>
            <Textarea
              id="invoiceNotes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Additional notes for the invoice..."
              rows={2}
            />
          </div>

          {depositPaid > 0 && (
            <div className="flex items-center gap-2 text-sm text-green-600 bg-green-50 p-3 rounded-lg">
              <Receipt className="h-4 w-4" />
              A payment receipt will be created for the deposit
            </div>
          )}
        </div>

        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleGenerateInvoice} disabled={loading}>
            {loading ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <FileText className="h-4 w-4 mr-2" />
                Generate Invoice
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
